services:
  _defaults:
    autowire: true
    autoconfigure: true

  Mike4Git\ChainBundle\Command\ListChainsCommand:
    tags:
      - { name: 'console.command' }
    public: true

  Mike4Git\ChainBundle\Registry\ChainHandlerRegistry:
    public: true

  Mike4Git\ChainBundle\Executor\ChainExecutor:
    arguments:
      $registry: '@Mike4Git\ChainBundle\Registry\ChainHandlerRegistry'
    public: true
