services:
  _defaults:
    autowire: true
    autoconfigure: true

  Mike4Git\ChainBundle\Registry\ChainHandlerRegistry:
    public: true

  Mike4Git\ChainBundle\Executor\ChainExecutor:
    arguments:
      $registry: '@Mike4Git\ChainBundle\Registry\ChainHandlerRegistry'
    public: true
